### PR TITLE
Added consultant company

### PR DESCRIPTION
**Pull request by DimopoulosElias**
When you are going to Consultant Information, you can put the name of your company.
On your template, add ΩCONSULTANT_COMPANYΩ where you want to place the name of your company.

### CODE REVIEW

**Comment by BuffaloWill** [comment]
@DimopoulosElias thanks for the pull request. I was on the fence at first with this but I can see the value where a company could have multiple groups and this would need to be reflected in a report. Cheers!

**Comment by DimopoulosElias** [comment]
@BuffaloWill In your templates under "Consultant Information" you have, among others, (Business Address, City, State, etc). You have chosen to "hard code" them in the template. I prefer to have the ability to change them from the UI (exactly like the consultant company, or the consultant name, etc). Fro example if we change the company's url, i don't have to deal with templates. I just change the url from the UI. I have made this changes in my fork. 
I would have pull request them, but i am not sure that you wanted that kind of changes.
If you are interested in, pls tell me to pull request.

**Comment by BuffaloWill** [comment]
@DimopoulosElias that makes sense; thanks for the feedback. One of my primary goals is to get serpico to the point where we would only need to modify templates for style changes and never for report/data information. At the same time I want to balance limiting changes to the database. 
Have tried User Defined Variables (https://github.com/MooseDojo/Serpico/wiki/User-Defined-Variables)?  For example adding a User Defined Variable for company url would add this functionality to the UI without having to modify the template every time.

**Comment by DimopoulosElias** [comment]
User defined vars, didn't work inside rows. I am not sure if i made sth wrong, i'll try it again. 
However the consultant company's details, personally i want them in the Consultant info.  
I believe it is sth like my name, or my e-mail. 
I use users vars, for things that are common for every report, but specialized for every customer. For example the executive summary paragraph, or the attack narrative.

**Pull request merged**
