### PR TITLE
Add support for CVSS Scoring.  Set cvss :true and dread :false in the…

### PR DESCRIPTION
**Pull request by l0gan**
… config.json file to make change take effect.  I am sure there is a better way of doing this, but this seems to work well enough.

### CODE REVIEW

**Comment by BuffaloWill** [comment]
@l0gan - thanks for the pull request! Good stuff. I need to look through this further and cherrypick from the modified files.

**Comment by BuffaloWill** [comment]
@l0gan I modified parts of the PR and pushed into the CVSS branch. If you get a chance please test and give feedback/issues. I will land by EOW after testing some more on my end.

Thanks!

**Comment by l0gan** [comment]
The limited testing I have done looks fine. The default report is setup for DREAD scoring, so maybe we should add a CVSS "Default Template"? I can get one together and submit a pull request for that if you want, just not sure when I will have it done.

**Comment by BuffaloWill** [comment]
Landed the CVSS branch. Thanks again @l0gan !!

**Pull request closed without merging**
